furniture/urls.py
from django.urls import path
from .views import list_furniture, new_furniture, delete_furniture, edit_furniture

app_name = 'furniture'

urlpatterns = [
    path('list/', list_furniture, name='list_furniture'),
    path('new/', new_furniture, name='new_furniture'),
    path('delete/<int:id>', delete_furniture, name='delete_furniture'),
    path('edit/<int:id>', edit_furniture, name='edit_furniture'),

]

home/urls.py
from django.urls import path
from .views import home

app_name = 'home'

urlpatterns = [
    path('', home, name='home'),
]

hometype/urls.py
from django.urls import path
from .views import list_hometype, new_hometype, delete_hometype, edit_hometype

app_name = 'hometype'

urlpatterns = [
    path('list/', list_hometype, name='list_hometype'),
    path('new/', new_hometype, name='new_hometype'),
    path('delete/<int:id>', delete_hometype, name='delete_hometype'),
    path('edit/<int:id>', edit_hometype, name='edit_hometype'),

]

roomstype/urls.py
from django.urls import path
from .views import list_roomstype, new_roomstype, delete_roomstype, edit_roomstype

app_name = 'roomstype'

urlpatterns = [
    path('list/', list_roomstype, name='list_roomstype'),
    path('new/', new_roomstype, name='new_roomstype'),
    path('delete/<int:id>', delete_roomstype, name='delete_roomstype'),
    path('edit/<int:id>', edit_roomstype, name='edit_roomstype'),

]

texturetype/urls.py
from django.urls import path
from .views import list_texturetype, new_texturetype, delete_texturetype, edit_texturetype

app_name = 'texturetype'

urlpatterns = [
    path('list/', list_texturetype, name='list_texturetype'),
    path('new/', new_texturetype, name='new_texturetype'),
    path('delete/<int:id>', delete_texturetype, name='delete_texturetype'),
    path('edit/<int:id>', edit_texturetype, name='edit_texturetype'),

]

woodwork/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('hometype/', include('hometype.urls')),
    path('furniture/', include('furniture.urls')),
    path('roomstype/', include('roomstype.urls')),
    path('texturetype/', include('texturetype.urls')),

]

home/views.py
from django.shortcuts import render

def home(request):
    context = {
        'title_scope':'WoodWork',
        'about':'Escolha sua opção de menu',
    }
    return render(request,'home.html',context)

home/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

    <head>
        <meta charset='utf-8'>
        <meta http-equiv='X-UA-Compatible' content='IE=edge'>
        <meta http-equiv="content-language" content="pt-br, en-US">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>WoodWork</title>
        <link href="{% static '/home/css/fontawesome/css/all.css' %}" rel="stylesheet">
        <link href="{% static '/home/css/base.css' %}" rel="stylesheet">
        <link href="{% static '/home/css/home.css' %}" rel="stylesheet">
        <link href="{% static '/roomstype/css/roomstype.css' %}" rel="stylesheet">

    </head>

    <body>
        <ul>
            <!--        
            <li><a href="#home">Home</a></li>
            <li><a href="#news">News</a></li>
            -->
            <li class="dropdown">
                <div class="dropdown-title">
                    <i class="fas fa-bars dropbtn"> <span class="dropdown-title-no-select">{{ title_scope }}</span> </i>
                </div>
                <div class="dropdown-content">
                    <a class="fas fa-poll-h" href="{% url 'furniture:list_furniture' %}"> <spam class="dropdown-content-menu"> Cadastro de Móveis </spam> </a>
                    <a class="fas fa-box" href="{% url 'roomstype:list_roomstype' %}"> <spam class="dropdown-content-menu"> Cadastro de Ambientes </spam> </a>
                    <a class="fas fa-hotel" href="{% url 'hometype:list_hometype' %}"> <spam class="dropdown-content-menu"> Cadastro de Imóveis </spam> </a>
                    <a class="fas fa-palette" href="{% url 'texturetype:list_texturetype' %}"><spam class="dropdown-content-menu"> Cadastro de Texturas </spam></a>
                    <hr>
                    <a class="fas fa-image" href="{% url 'texturetype:list_texturetype' %}"><spam class="dropdown-content-menu"> Registrar Imagem </spam></a>
                    <hr>
                    <a class="fas fa-home" href="{% url 'home:home' %}"> <spam class="dropdown-content-menu"> Home </spam></a>
                </div>
            </li>
        </ul>

        <div class="list-images-cicle">
            <div class="images-cicle">
                    <div class="images-title" >
                        <img class="images-furniture" src="{% static '/images/1.jpeg' %}" ald="Roupeiro">
                        <legend class="images-legend" >Roupeiro</legend>
                    </div>
                    <div class="images-title" >
                        <img class="images-furniture" src="{% static '/images/2.jpeg' %}" ald="Cozinha">
                        <legend class="images-legend" >Cozinha</legend>
                    </div>
                    <div class="images-title" >
                        <img class="images-furniture" src="{% static '/images/3.jpeg' %}" ald="Banheiro">
                        <legend class="images-legend" >Banheiro</legend>
                    </div>
                    <div class="images-title" >
                        <img class="images-furniture" src="{% static '/images/4.jpeg' %}" ald="Painel">
                        <legend class="images-legend" >Painel</legend>
                    </div>

            </div>
        </div>

        {% block content %} {% endblock %}

    </body>

</html>
<footer>
    <script src="{% static '/home/js/home.js' %}"></script>
</footer>

home/templates/home.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div id="myBtnfurniture">
    <button class="btn active" onclick="filterSelection('all')"> Todos</button>
    <button class="btn" onclick="filterSelection('roupeiro')"> Roupeiros</button>
    <button class="btn" onclick="filterSelection('cozinha')"> Cozinhas</button>
    <button class="btn" onclick="filterSelection('banheiro')"> Banheiros</button>
    <button class="btn" onclick="filterSelection('painel')"> Paineis</button>
</div>

    <div class="cards-container">
        <div class="row">

            <div class="filterDiv cozinha column">
                <div class="card">
                    <img class="demo cursor product-image" id="product_1"
                        src="{% static '/images/1.jpeg' %}" alt="Cozinha">
                </div>
            </div>

            <div class="filterDiv cozinha column">
                <div class="card">
                    <img class="demo cursor product-image" id="product_2"
                        src="{% static '/images/2.jpeg' %}" alt="Cozinha">
                </div>
            </div>

            <div class="filterDiv cozinha column">
                <div class="card">
                    <img class="demo cursor product-image" id="product_3"
                        src="{% static '/images/3.jpeg' %}" alt="Cozinha">
                </div>
            </div>
            <div class="filterDiv cozinha column">
                <div class="card">
                    <img class="demo cursor product-image" id="product_4"
                        src="{% static '/images/4.jpeg' %}" alt="Cozinha">
                </div>
            </div>
            <div class="filterDiv cozinha column">
                <div class="card">
                    <img class="demo cursor product-image" id="product_5"
                        src="{% static '/images/5.jpeg' %}" alt="Cozinha">
                </div>
            </div>
            <div class="filterDiv cozinha column">
                <div class="card">
                    <img class="demo cursor product-image" id="product_6"
                        src="{% static '/images/6.jpeg' %}" alt="Cozinha">
                </div>
            </div>
            <div class="filterDiv roupeiro column">
                <div class="card">
                    <img class="demo cursor product-image" id="product_7"
                        src="{% static '/images/7.jpeg' %}" alt="Roupeiro">
                </div>
            </div>
            <div class="filterDiv roupeiro column">
                <div class="card">
                    <img class="demo cursor product-image" id="product_8"
                        src="{% static '/images/8.jpeg' %}" alt="Roupeiro">
                </div>
            </div>
            <div class="filterDiv roupeiro column">
                <div class="card">
                    <img class="demo cursor product-image" id="product_9"
                        src="{% static '/images/9.jpeg' %}" alt="Roupeiro">
                </div>
            </div>
            <div class="filterDiv roupeiro column">
                <div class="card">
                    <img class="demo cursor product-image" id="product_10"
                        src="{% static '/images/10.jpeg' %}" alt="Roupeiro">
                </div>
            </div>
            <div class="filterDiv roupeiro column">
                <div class="card">
                    <img class="demo cursor product-image" id="product_11"
                        src="{% static '/images/11.jpeg' %}" alt="Roupeiro">
                </div>
            </div>
            <div class="filterDiv roupeiro column">
                <div class="card">
                    <img class="demo cursor product-image" id="product_12"
                        src="{% static '/images/12.jpeg' %}" alt="Roupeiro">
                </div>
            </div>
            <div class="filterDiv banheiro column">
                <div class="card">
                    <img class="demo cursor product-image" id="product_13"
                        src="{% static '/images/13.jpeg' %}" alt="Banheiro">
                </div>
            </div>
            <div class="filterDiv banheiro column">
                <div class="card">
                    <img class="demo cursor product-image" id="product_14"
                        src="{% static '/images/14.jpeg' %}" alt="Banheiro">
                </div>
            </div>
            <div class="filterDiv banheiro column">
                <div class="card">
                    <img class="demo cursor product-image" id="product_15"
                        src="{% static '/images/15.jpeg' %}" alt="Banheiro">
                </div>
            </div>
            <div class="filterDiv painel column">
                <div class="card">
                    <img class="demo cursor product-image" id="product_16"
                        src="{% static '/images/16.jpeg' %}" alt="Painel">
                </div>
            </div>
            <div class="filterDiv painel column">
                <div class="card">
                    <img class="demo cursor product-image" id="product_16"
                        src="{% static '/images/17.jpeg' %}" alt="Painel">
                </div>
            </div>
            <div class="filterDiv painel column">
                <div class="card">
                    <img class="demo cursor product-image" id="product_16"
                        src="{% static '/images/18.jpeg' %}" alt="Painel">
                </div>
            </div>

        </div>
    </div>

<!-- The Modal -->
<div class="modal modal-image">
    <span class="close">&times;</span>
    <img class="modal-content">
    <div id="caption"></div>
</div>


{% endblock %}