home/urls.py
from django.urls import path
from .views import home

app_name = 'home'

urlpatterns = [
    path('', home, name='home'),
]

texturetype/urls.py
from django.urls import path
from .views import list_texturetype, new_texturetype, delete_texturetype, edit_texturetype

app_name = 'texturetype'

urlpatterns = [
    path('list/', list_texturetype, name='list_texturetype'),
    path('new/', new_texturetype, name='new_texturetype'),
    path('delete/<int:id>', delete_texturetype, name='delete_texturetype'),
    path('edit/<int:id>', edit_texturetype, name='edit_texturetype'),

]

woodwork/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('hometype/', include('hometype.urls')),
    path('furniture/', include('furniture.urls')),
    path('roomstype/', include('roomstype.urls')),
    path('texturetype/', include('texturetype.urls')),

]

texturetype/models.py
from django.db import models

class TextureType(models.Model):
    name = models.CharField('Nome da Texture', max_length=100, null=False, blank=False, unique=True)

    class Meta:
        verbose_name = 'Textura'    
        verbose_name_plural = 'Texturas'
        ordering = ['name']

    def __str__(self):
        return self.name    

texturetype/forms.py
from django import forms
from .models import TextureType

class TextureTypeForm(forms.ModelForm):
    class Meta:
        model = TextureType

        fields = ('__all__')
  

texturetype/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import TextureType
from .forms import TextureTypeForm
from django.db import IntegrityError
from django.contrib import messages
from utils import normalize

app_name = 'texturetype'

def list_texturetype(request):
    template_name = 'list_texturetype.html'
    texturetypes = TextureType.objects.all()

    context = {
        'title_scope':'Textures - Listar',
        'records':texturetypes,
    }
    return render(request, template_name, context)

def new_texturetype(request):
    template_name = 'new_texturetype.html'
    form = TextureTypeForm(request.POST or None)
    if form.is_valid():
        try:
            texture = form.save(commit=False)
            texture.name = normalize(texture.name.title())
            texture.save()
        except IntegrityError as e:
            if 'UNIQUE' in str(e).upper():
                messages.add_message(request, messages.INFO, 'Textura "'+texture.name+'" já cadastrada!')
            else:
                messages.add_message(request, messages.INFO, 'Erro ao incluir a texture "'+texture.name+'! '+str(e))
            return redirect('texturetype:new_texturetype')
        return redirect('texturetype:list_texturetype')
    else:
        messages.add_message(request, messages.INFO, form.errors)

    context = {
        'title_scope':'Textures - Incluir',
        'records':form,
    }
    return render(request, template_name, context)

def delete_texturetype(request, id):
    texturetype = TextureType.objects.filter(id=id)
    if texturetype:
        texturetype.delete()
    return redirect('texturetype:list_texturetype')

def edit_texturetype(request, id):
    template_name = 'edit_texturetype.html'
    texturetype = TextureType.objects.get(pk=id)
    form = TextureTypeForm(request.POST, instance=texturetype)
    if request.method == 'POST':
        if form.is_valid():
            try:
                texture = form.save(commit=False)
                texture.name = normalize(texture.name.title())
                texture.save()
            except IntegrityError as e:
                if 'UNIQUE' in str(e).upper():
                    messages.add_message(request, messages.INFO, 'Textura "'+texture.name+'" já cadastrada!')
                else:
                    messages.add_message(request, messages.INFO, 'Erro ao incluir a textura "'+room.name+'! '+str(e))
                return redirect('texturetype:new_texturetype')
        return redirect('texturetype:list_texturetype')
    else:
        context = {
            'title_scope':'Texture - Alterar',
            'record':texturetype,
        }
        return render(request, template_name, context)

texturetype/templates/edit_texturetype.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<h1>{{ about }}</h1>
<div class="container">
    <form method="POST" enctype="multipart/form-data" action="#">
        {% csrf_token %}
        <label for="fname">Nome da Textura</label>
        <input type="text" id="name" name="name" value="{{ record.name }}" placeholder="Digite aqui: Lino, Marroco..." autofocus>

        <div class="input_button">
            <input type="submit" value="Salvar">
        </div>

        {% if messages %}
        <div class="display_error">
            {% for message in messages %}
            {{ message|capfirst }}
            {% endfor %}
        </div>
        {% endif %}
    </form>
</div>


{% endblock %}

texturetype/templates/list_texturetype.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container">
    
    <div class="insert-count"> 
        <i class="fas fa-star-half-alt record-count"> {{ records.count }} Textura{{ records.count|pluralize }} </i>

        <a class="cursor-style" href="{% url 'texturetype:new_texturetype' %}">
            <i class="fas fa-plus-square cursor-style"></i>
        </a>
    </div>
    <form action="#">
        <table id="customers">
            <tr>
                <th>Texturas</th>
                <th style="text-align: center; width: 20px;">Ações</th>
            </tr>
            {% for record in records %}
                <tr>
                    <td>{{ record.name }}</td>
                    <td>
                        <div id="actions-buttons">
                            <a href="{% url 'texturetype:edit_texturetype' record.id %}"><i class="fas fa-edit cursor-style"></i></a>
                            <a href="{% url 'texturetype:delete_texturetype' record.id %}"><i class="fas fa-trash-alt cursor-style"></i></a>
                        </div>
                    </td>
                </tr>
            {% endfor %}
        </table>
    </form>
</div>
{% endblock %}

texturetype/templates/new_texturetype.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<h1>{{ about }}</h1>
<div class="container">

    <form method="POST" enctype="multipart/form-data" action="#">
        {% csrf_token %}
        <label for="fname">Nome da Textura</label>
        <input type="text" id="name" name="name" value="{{ record.name }}" placeholder="Digite aqui: Lino, Marroco..." autofocus>
<!-- 
        <label for="country">Country</label>
        <select id="country" name="country">
            <option value="australia">Australia</option>
            <option value="canada">Canada</option>
            <option value="usa">USA</option>
        </select>
 --> 
        <div class="input_button">
            <input type="submit" value="Salvar">
        </div>

        {% if messages %}
            <div class="display_error">
                {% for message in messages %}
                    {{ message|capfirst }}
                {% endfor %}
            </div>
        {% endif %}
    </form>
</div>


{% endblock %}