home/urls.py
from django.urls import path
from .views import home

app_name = 'home'

urlpatterns = [
    path('', home, name='home'),
]

hometype/urls.py
from django.urls import path
from .views import list_hometype, new_hometype, delete_hometype, edit_hometype

app_name = 'hometype'

urlpatterns = [
    path('list/', list_hometype, name='list_hometype'),
    path('new/', new_hometype, name='new_hometype'),
    path('delete/<int:id>', delete_hometype, name='delete_hometype'),
    path('edit/<int:id>', edit_hometype, name='edit_hometype'),

]

woodwork/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('hometype/', include('hometype.urls')),
    path('furniture/', include('furniture.urls')),
    path('roomstype/', include('roomstype.urls')),
    path('texturetype/', include('texturetype.urls')),

]

hometype/models.py
from django.db import models

class HomeType(models.Model):
    name = models.CharField('Nome do Imóvel', max_length=100, null=False, blank=False, unique=True)

    class Meta:
        verbose_name = 'Imóvel'    
        verbose_name_plural = 'Imóveis'
        ordering = ['name']

    def __str__(self):
        return self.name    

hometype/forms.py
from django import forms
from .models import HomeType

class HomeTypeForm(forms.ModelForm):
    class Meta:
        model = HomeType

        fields = ('__all__')
  

hometype/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import HomeType
from .forms import HomeTypeForm
from django.db import IntegrityError
from django.contrib import messages
from utils import normalize

app_name = 'hometype'

def list_hometype(request):
    template_name = 'list_hometype.html'
    hometypes = HomeType.objects.all()

    context = {
        'title_scope':'Imóveis - Listar',
        'records':hometypes,
    }
    return render(request, template_name, context)

def new_hometype(request):
    template_name = 'new_hometype.html'
    form = HomeTypeForm(request.POST or None)
    if form.is_valid():
        try:
            home = form.save(commit=False)
            home.name = normalize(home.name.title())
            home.save()
        except IntegrityError as e:
            if 'UNIQUE' in str(e).upper():
                messages.add_message(request, messages.INFO, 'Imóvel "'+home.name+'" já cadastrado!')
            else:
                messages.add_message(request, messages.INFO, 'Erro ao incluir o imóvel "'+home.name+'! '+str(e))
            return redirect('hometype:new_hometype')
        return redirect('hometype:list_hometype')
    else:
        messages.add_message(request, messages.INFO, form.errors)

    context = {
        'title_scope':'Imóveis - Incluir',
        'records':form,
    }
    return render(request, template_name, context)

def delete_hometype(request, id):
    hometype = HomeType.objects.filter(id=id)
    if hometype:
        hometype.delete()
    return redirect('hometype:list_hometype')

def edit_hometype(request, id):
    template_name = 'edit_hometype.html'
    hometype = HomeType.objects.get(pk=id)
    form = HomeTypeForm(request.POST, instance=hometype)
    if request.method == 'POST':
        if form.is_valid():
            try:
                home = form.save(commit=False)
                home.name = normalize(home.name.title())
                home.save()
            except IntegrityError as e:
                if 'UNIQUE' in str(e).upper():
                    messages.add_message(request, messages.INFO, 'Imóvel "'+home.name+'" já cadastrado!')
                else:
                    messages.add_message(request, messages.INFO, 'Erro ao incluir o imóvel "'+home.name+'! '+str(e))
                return redirect('hometype:new_hometype')
        return redirect('hometype:list_hometype')
    else:
        context = {
            'title_scope':'Imóveis - Alterar',
            'record':hometype,
        }
        return render(request, template_name, context)

hometype/templates/edit_hometype.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<h1>{{ about }}</h1>
<div class="container">
    <form method="POST" enctype="multipart/form-data" action="#">
        {% csrf_token %}
        <label for="fname">Nome do Imóvel</label>
        <input type="text" id="name" name="name" value="{{ record.name }}" placeholder="Digite aqui: Casa, Apartamento..." autofocus>

        <div class="input_button">
            <input type="submit" value="Salvar">
        </div>

        {% if messages %}
        <div class="display_error">
            {% for message in messages %}
            {{ message|capfirst }}
            {% endfor %}
        </div>
        {% endif %}
    </form>
</div>


{% endblock %}

hometype/templates/list_hometype.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container">
    
    <div class="insert-count"> 
        <i class="fas fa-star-half-alt record-count"> {{ records.count }} Imóveis </i>

        <a class="cursor-style" href="{% url 'hometype:new_hometype' %}">
            <i class="fas fa-plus-square cursor-style"></i>
        </a>
    </div>
    <form action="#">
        <table id="customers">
            <tr>
                <th>Imóveis</th>
                <th style="text-align: center; width: 20px;">Ações</th>
            </tr>
            {% for record in records %}
                <tr>
                    <td>{{ record.name }}</td>
                    <td>
                        <div id="actions-buttons">
                            <a href="{% url 'hometype:edit_hometype' record.id %}"><i class="fas fa-edit cursor-style"></i></a>
                            <a href="{% url 'hometype:delete_hometype' record.id %}"><i class="fas fa-trash-alt cursor-style"></i></a>
                        </div>
                    </td>
                </tr>
            {% endfor %}
        </table>
    </form>
</div>
{% endblock %}

hometype/templates/new_hometype.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<h1>{{ about }}</h1>
<div class="container">

    <form method="POST" enctype="multipart/form-data" action="#">
        {% csrf_token %}
        <label for="fname">Nome do Imóvel</label>
        <input type="text" id="name" name="name" value="{{ record.name }}" placeholder="Digite aqui: Casa, Apartamento..." autofocus>
<!-- 
        <label for="country">Country</label>
        <select id="country" name="country">
            <option value="australia">Australia</option>
            <option value="canada">Canada</option>
            <option value="usa">USA</option>
        </select>
 --> 
        <div class="input_button">
            <input type="submit" value="Salvar">
        </div>

        {% if messages %}
            <div class="display_error">
                {% for message in messages %}
                    {{ message|capfirst }}
                {% endfor %}
            </div>
        {% endif %}
    </form>
</div>


{% endblock %}