furniture/urls.py
from django.urls import path
from .views import list_furniture, new_furniture, delete_furniture, edit_furniture

app_name = 'furniture'

urlpatterns = [
    path('list/', list_furniture, name='list_furniture'),
    path('new/', new_furniture, name='new_furniture'),
    path('delete/<int:id>', delete_furniture, name='delete_furniture'),
    path('edit/<int:id>', edit_furniture, name='edit_furniture'),

]

home/urls.py
from django.urls import path
from .views import home

app_name = 'home'

urlpatterns = [
    path('', home, name='home'),
]

woodwork/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('hometype/', include('hometype.urls')),
    path('furniture/', include('furniture.urls')),
    path('roomstype/', include('roomstype.urls')),
    path('texturetype/', include('texturetype.urls')),

]

furniture/models.py
from django.db import models

class Furniture(models.Model):
    name = models.CharField('Nome do Móvel', max_length=100, null=False, blank=False, unique=True)

    class Meta:
        verbose_name = 'Móvel'    
        verbose_name_plural = 'Móveis'
        ordering = ['name']

    def __str__(self):
        return self.name    

furniture/forms.py
from django import forms
from .models import Furniture

class FurnitureForm(forms.ModelForm):
    class Meta:
        model = Furniture

        fields = ('__all__')
  

furniture/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Furniture
from .forms import FurnitureForm
from django.db import IntegrityError
from django.contrib import messages
from utils import normalize

app_name = 'furniture'

def list_furniture(request):
    template_name = 'list_furniture.html'
    furnitures = Furniture.objects.all()

    context = {
        'title_scope':'Móveis - Listar',
        'records':furnitures,
    }
    return render(request, template_name, context)

def new_furniture(request):
    template_name = 'new_furniture.html'
    form = FurnitureForm(request.POST or None)
    if form.is_valid():
        try:
            furniture = form.save(commit=False)
            furniture.name = normalize(furniture.name.title())
            furniture.save()
        except IntegrityError as e:
            if 'UNIQUE' in str(e).upper():
                messages.add_message(request, messages.INFO, 'Imóvel "'+furniture.name+'" já cadastrado!')
            else:
                messages.add_message(request, messages.INFO, 'Erro ao incluir o imóvel "'+furniture.name+'! '+str(e))
            return redirect('furniture:new_furniture')
        return redirect('furniture:list_furniture')
    else:
        messages.add_message(request, messages.INFO, form.errors)

    context = {
        'title_scope':'Móveis - Incluir',
        'records':form,
    }
    return render(request, template_name, context)

def delete_furniture(request, id):
    furniture = Furniture.objects.filter(id=id)
    if furniture:
        furniture.delete()
    return redirect('furniture:list_furniture')

def edit_furniture(request, id):
    template_name = 'edit_furniture.html'
    furniture = Furniture.objects.get(pk=id)
    form = FurnitureForm(request.POST, instance=furniture)
    if request.method == 'POST':
        if form.is_valid():
            try:
                home = form.save(commit=False)
                home.name = normalize(home.name.title())
                home.save()
            except IntegrityError as e:
                if 'UNIQUE' in str(e).upper():
                    messages.add_message(request, messages.INFO, 'Imóvel "'+home.name+'" já cadastrado!')
                else:
                    messages.add_message(request, messages.INFO, 'Erro ao incluir o imóvel "'+home.name+'! '+str(e))
                return redirect('furniture:new_furniture')
        return redirect('furniture:list_furniture')
    else:
        context = {
            'title_scope':'Imóveis - Alterar',
            'record':furniture,
        }
        return render(request, template_name, context)

furniture/templates/edit_furniture.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<h1>{{ about }}</h1>
<div class="container">
    <form method="POST" enctype="multipart/form-data" action="#">
        {% csrf_token %}
        <label for="fname">Nome do Móvel</label>
        <input type="text" id="name" name="name" value="{{ record.name }}" placeholder="Digite aqui: Casa, Apartamento..." autofocus>

        <div class="input_button">
            <input type="submit" value="Salvar">
        </div>

        {% if messages %}
        <div class="display_error">
            {% for message in messages %}
            {{ message|capfirst }}
            {% endfor %}
        </div>
        {% endif %}
    </form>
</div>


{% endblock %}

furniture/templates/list_furniture.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container">
    
    <div class="insert-count"> 
        <i class="fas fa-star-half-alt record-count"> {{ records.count }} Móveis </i>

        <a class="cursor-style" href="{% url 'furniture:new_furniture' %}">
            <i class="fas fa-plus-square cursor-style"></i>
        </a>
    </div>
    <form action="#">
        <table id="customers">
            <tr>
                <th>Móveis</th>
                <th style="text-align: center; width: 20px;">Ações</th>
            </tr>
            {% for record in records %}
                <tr>
                    <td>{{ record.name }}</td>
                    <td>
                        <div id="actions-buttons">
                            <a href="{% url 'furniture:edit_furniture' record.id %}"><i class="fas fa-edit cursor-style"></i></a>
                            <a href="{% url 'furniture:delete_furniture' record.id %}"><i class="fas fa-trash-alt cursor-style"></i></a>
                        </div>
                    </td>
                </tr>
            {% endfor %}
        </table>
    </form>
</div>
{% endblock %}

furniture/templates/new_furniture.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<h1>{{ about }}</h1>
<div class="container">

    <form method="POST" enctype="multipart/form-data" action="#">
        {% csrf_token %}
        <label for="fname">Nome do Móvel</label>
        <input type="text" id="name" name="name" value="{{ record.name }}" placeholder="Digite aqui: Casa, Apartamento..." autofocus>
<!-- 
        <label for="country">Country</label>
        <select id="country" name="country">
            <option value="australia">Australia</option>
            <option value="canada">Canada</option>
            <option value="usa">USA</option>
        </select>
 --> 
        <div class="input_button">
            <input type="submit" value="Salvar">
        </div>

        {% if messages %}
            <div class="display_error">
                {% for message in messages %}
                    {{ message|capfirst }}
                {% endfor %}
            </div>
        {% endif %}
    </form>
</div>


{% endblock %}